### ISSUE TITLE
[SOLVED] cropped sections

### ISSUE THREAD

**Issue by zenny** [PlatinumClaridge/LARBS#2]
Hi,

A visual issue with the boarder around the open windows, particularly when in applications like firefox. The bottom of the page gets cropped, see the find bar at the bottom of https://paste.pics/92VRW (Direct link: https://i.paste.pics/92VRW.png) This prevents navigation of the searched items, in my case.

Isn't that a good idea to remove the entire wasted space of the screen of about 10px all around to get rid of the kind of annoyances? 

Cheers,
/z

**Comment by PlatinumClaridge** [comment]
I haven’t experienced this issue. But what you could do is edit the config.h file in dwm. There’s values at the top that determine gap size. Then just recompile and super+F2 to restart dwm.

**Comment by zenny** [comment]
> I haven’t experienced this issue. But what you could do is edit the config.h file in dwm. There’s values at the top that determine gap size. Then just recompile and super+F2 to restart dwm.

@PlatinumClaridge Thanks, already done with just 1px boarder on all sides.
